base:
  log:
    filename: ./logs/service.log
    level: debug
    max_size: 32
    max_backups: 5
    max_age: 7
    compress: false
    enable_stdout: true
  gateway:
    enabled: true
    ttl: 15
    weight: 10
    provider:
      endpoints:
        - 127.0.0.1:2379
      username: ""
      password: ""
      dial_timeout: 5
      namespace: traefik
  registry:
    enabled: true
    weight: 10
    provider:
      endpoints:
        - 127.0.0.1:2379
      username: ""
      password: ""
      dial_timeout: 5
      load_balancer_strategy: 0
